from PIL import Image
import io
from easyocr import Reader
from pathlib import Path
from fpdf import FPDF

class ImgsToNote:
    """A class that converts a gallery of images and generates either a pdf
    of unique images or a study note in a pdf based on the images texts"""

    def __init__(self, imgs: list[bytes] | None = None) -> None:
        if imgs == None:
            imgs = []

        self.text = ""
        self.image_gallery: list[bytes] = []
        self.ocr = Reader(['en'])
        self.bytelen = 0

        for img in imgs:
            self.insert_image(img)

            # Amortize the efficiency of any image comparison/processing
            if self.bytelen == 0: 
                self.bytelen = len(img)


    def get_gallery(self) -> list[Image.Image]:
        ret = []
        for i in self.image_gallery:
            ret.append(Image.open(io.BytesIO(i)))
        
        return ret


    def insert_image(self, img: bytes) -> None:
        "Inserts the image into the 'note' if it's a new image from previous"
        if self.bytelen == 0:
                self.bytelen = len(img)

        # Compare to the last inserted image
        if len(self.image_gallery) > 0:
            if self.compare_image(img, self.image_gallery[-1], self.bytelen):
                return None
        
        self.update_text(img)


    def update_text(self, img: bytes) -> None:
        "Adds an to gallery and updates text"
        read = "".join(self.ocr.readtext(img, detail=0))
        self.text = self.text + read + "\n"
        self.image_gallery.append(img)

    
    def make_slide(self, path: Path | str | None = None) -> bytearray | None:
        """Generates a pdf of all the images to the desired path"""
        pdf = FPDF(orientation="P", unit="pt", format="A4")
        pdf.add_page()

        for img in self.image_gallery:
            with io.BytesIO(img) as data:
                pdf.image(data, w=500, h=400, x=int(pdf.w / 2 - 250))

                # Make a gap between each image
                pdf.set_font("Times", size=24)
                pdf.cell(w=pdf.w, h=30, new_x='LMARGIN', new_y='NEXT') 
        
        if path == None:
            return pdf.output()
        else:
            pdf.output(path)


    def make_note(self, path: Path | str | None = None) -> bytearray | None:
        notetext = self.summarize(self.text)

        pdf = FPDF(orientation="P", unit="pt", format="A4")
        pdf.add_page()
        pdf.set_font("Times", size=12)
        pdf.multi_cell(w=0,h=30, txt=notetext)

        if path == None:
            return pdf.output()
        else:
            pdf.output(path)
    

    @staticmethod
    def summarize(text):
        "Generates a summarized and study-formatted note generated by CHATGPT based on the input"

        import openai
        import os
        openai.api_key = os.getenv('gptkey')

        chat = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
                {"role": "system", "content": "You summarize text and fill in details to generate a study note"},
                {"role": "user", "content": f"Convert the following text into a study note and add missing details: {text}"}
            ]
        )

        return str(chat['choices'][0]['message']['content'])


    @staticmethod
    def compare_image(img1: bytes, img2: bytes, length: int, factor=0.75) -> bool:
        """Compares the similarity of two images if it's within a factor 0 -> 1 assuming equal sizes.
        Use a sample of 1/10 of the pixels from the middle of the image"""
        equal = 0

        samplesize = int(length / 20) # x2 for both sides of half
        half = int(length / 2)
        for i in range(half - samplesize, half + samplesize):
            if img1[i] == img2[i]:
                equal += 1

        if equal / (samplesize * 2) >= factor:
            return True 

        return False
